# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."quetre" = {
    image = "quay.io/pussthecatorg/quetre:latest";
    environment = {
      "CACHE_PERIOD" = "1h";
      "NODE_ENV" = "production";
      "PORT" = "3000";
      "REDIS_TTL" = "3600";
      "REDIS_URL" = "quetre-redis:6379";
    };
    ports = [
      "127.0.0.1:13000:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=quetre"
      "--network=quatre_default"
    ];
  };
  systemd.services."podman-quetre" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-quatre_default.service"
    ];
    requires = [
      "podman-network-quatre_default.service"
    ];
    partOf = [
      "podman-compose-quatre-root.target"
    ];
    wantedBy = [
      "podman-compose-quatre-root.target"
    ];
  };
  virtualisation.oci-containers.containers."quetre-redis" = {
    image = "docker.io/redis:alpine";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=quetre-redis"
      "--network=quatre_default"
    ];
  };
  systemd.services."podman-quetre-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-quatre_default.service"
    ];
    requires = [
      "podman-network-quatre_default.service"
    ];
    partOf = [
      "podman-compose-quatre-root.target"
    ];
    wantedBy = [
      "podman-compose-quatre-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-quatre_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f quatre_default";
    };
    script = ''
      podman network inspect quatre_default || podman network create quatre_default
    '';
    partOf = [ "podman-compose-quatre-root.target" ];
    wantedBy = [ "podman-compose-quatre-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-quatre-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
