keys:
  - &personal age1rl4wtr4hj2mxp2rcdk2kuahtqmfx7e5meadsukxljl0l054eccksus4s2n
  - &articuno age1v57lt42hl9et5x7asxad6gkg9ga0gqd7swvnxs3mpuuyhzsspqgqasz3ch
  - &charizard age1yhsl8v77jja50pgtg6yklddfe2uprs7y2l8lx6595e3sntjj3gjq98he3a
  - &eevee age1zds0dt80guzvrkdpz962qe9tmjz4aa9cz8937r4tyn3tqy8q6f6qxdmp59
  - &flareon age1l844clz38nt5mq6kg5m0wl64p398dn0j3hm5jzy8ag0d302q5awqep73jx
  - &machamp age1k5e5uk0897ne5lrvmhhgn6am5cr32l2w7aa4ldapncwluv0rqekspj8w97

creation_rules:
  - path_regex: secrets/secrets.yaml
    key_groups:
      - age:
        - *personal

  - path_regex: nixos/hosts/articuno/secrets.yaml
    key_groups:
      - age:
        - *personal
        - *articuno

  - path_regex: nixos/hosts/charizard/secrets.yaml
    key_groups:
      - age:
        - *personal
        - *charizard
          
  - path_regex: nixos/hosts/eevee/secrets.yaml
    key_groups:
      - age:
        - *personal
        - *eevee

  - path_regex: nixos/hosts/flareon/secrets.yaml
    key_groups:
      - age:
        - *personal
        - *flareon
          
  - path_regex: nixos/hosts/machamp/secrets.yaml
    key_groups:
      - age:
        - *personal
        - *machamp

  - path_regex: nixos/hosts/moltres/secrets.yaml
    key_groups:
      - age:
        - *personal
        # - *moltres
          
  - path_regex: nixos/hosts/zapados/secrets.yaml
    key_groups:
      - age:
        - *personal
        # - *zapados

  - path_regex: nixos/modules/services/k3s/secrets.yaml
    key_groups:
      - age:
        - *personal
        - *articuno
        # - *moltres
        # - *zapados
        - *eevee
