keys:
  - &personal age1rl4wtr4hj2mxp2rcdk2kuahtqmfx7e5meadsukxljl0l054eccksus4s2n
  - &work age1gzstgq4mmvmx40jna6cjhuw7lzkcza3hkzwnnqvv3svemtr8reasqj052x
  - &articuno age1v57lt42hl9et5x7asxad6gkg9ga0gqd7swvnxs3mpuuyhzsspqgqasz3ch
  - &charizard age1cjhxs524nj7r0z2cmx3kf4vpscj8fxy0wmnxuy6nnfzt4dtahevsskgrus
  - &flareon age1l844clz38nt5mq6kg5m0wl64p398dn0j3hm5jzy8ag0d302q5awqep73jx
  - &jolteon age13qley8lnkqspu8yda95vqsvkrnfjmpm6m7e8um9gtm3yd8a4c34spzfx79
  - &moltres age183ss93pcc9vxxscndjktthj3jdrc2vqzg06dyd7kw3htgxsdmedqr3fj9q
  - &pikachu age1rvv0m2d5weqgnsf7cv7k2wv8rkgqd06pcmpf98j98m7mkf2a5gwsr2eqja
  - &tentacool age1k3ejfs0t5xavhw7xje2k7263np65la6ek0a0fz3y926t5qykwvnqxhteps
  - &zapados age1z37rwn90f923pdhjtcsw2r8a48hwsuh73xjswjj8z7qr3kp3aeyqdamr5f
  - &schwem-io age1fnlep954kqzdy62qpzap8ex0xm3xzcd9rau52rgewt7rtwn2huaqg593p9

creation_rules:
  # host secrets
  - path_regex: nixos/hosts/articuno/secrets.yaml
    key_groups:
      - age:
          - *personal
          - *articuno

  - path_regex: nixos/hosts/charizard/secrets.yaml
    key_groups:
      - age:
          - *personal
          - *charizard

  - path_regex: nixos/hosts/flareon/secrets.yaml
    key_groups:
      - age:
          - *personal
          - *flareon

  - path_regex: nixos/hosts/jolteon/secrets.yaml
    key_groups:
      - age:
          - *personal
          - *jolteon

  - path_regex: nixos/hosts/moltres/secrets.yaml
    key_groups:
      - age:
          - *personal
          - *moltres

  - path_regex: nixos/hosts/pikachu/secrets.yaml
    key_groups:
      - age:
          - *personal
          - *pikachu

  - path_regex: nixos/hosts/tentacool/secrets.yaml
    key_groups:
      - age:
          - *personal
          - *tentacool

  - path_regex: nixos/hosts/zapados/secrets.yaml
    key_groups:
      - age:
          - *personal
          - *zapados

  # home secrets
  - path_regex: ^(./)?secrets/home/.*.(yaml|json|env)
    key_groups:
      - age:
          - *personal
          - *charizard
          - *pikachu

  # nixos secrets
  - path_regex: ^(./)?secrets/nixos/.*.(yaml|json|env)
    key_groups:
      - age:
          - *personal
          - *articuno
          - *charizard
          - *flareon
          - *jolteon
          - *moltres
          - *pikachu
          - *tentacool
          - *zapados

  # server secrets
  - path_regex: ^(./)?secrets/server/.*.(yaml|json|env)
    key_groups:
      - age:
          - *personal
          - *articuno
          - *charizard
          - *flareon
          - *jolteon
          - *moltres
          - *pikachu
          - *tentacool
          - *zapados

  # TODO: sunset these pathways
  - path_regex: ^(./)?home/(.*/)?(.*/)?.*.(env|json|yaml)
    key_groups:
      - age:
          - *personal
          - *charizard
          - *schwem-io

  - path_regex: ^(./)?(nixos/)?(containers|modules|network|services|server)/(.*/)?(.*/)?(.*.yaml|.env)
    key_groups:
      - age:
          - *personal
          - *articuno
          - *charizard
          - *flareon
          - *jolteon
          - *moltres
          - *tentacool
          - *zapados
