keys:
  - &personal age1rl4wtr4hj2mxp2rcdk2kuahtqmfx7e5meadsukxljl0l054eccksus4s2n
  - &moltres age1ynhtuk2g3ek9svvuysynlnxkp5vffgylkedzhhaa9q4g9l8huf3sktz6lc

creation_rules:
  - path_regex: secrets/secrets.yaml
    key_groups:
      - age:
        - *personal
          
  - path_regex: secrets/keys/keys.yaml
    key_groups:
      - age:
        - *personal
