root: swap: {
  imports = [
    ./server.nix

    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk"];

  # disks are generated by racknerd at launch -- just use them instead of btrfs
  fileSystems."/" = {
    device = root;
    fsType = "ext4";
  };

  swapDevices = [
    {device = swap;}
  ];
}
