[colors]
foreground = "#D4BE98"
background = "#1D2021"
cursor_bg = "#D4BE98"
cursor_border = "#D4BE98"
cursor_fg = "#1D2021"
selection_bg = "#D4BE98"
selection_fg = "#3C3836"

ansi = [
	"#1d2021", # bg
	"#ea6962", # red
	"#a9b665", # green
	"#d8a657", # yellow
	"#7daea3", # blue
	"#d3869b", # purple
	"#89b482", # aqua
	"#d4be98", # gray
]

brights = [
	"#eddeb5", # gray
	"#ea6962", # red 
	"#a9b665", # green
	"#d8a657", # yellow
	"#7daea3", # blue
	"#d3869b", # purple
	"#89b482", # aqua
	"#d4be98", # fg
]

[metadata]
aliases = []
name = "GruvboxDarkMaterialHard"
origin_url = "https://github.com/mbadolato/iTerm2-Color-Schemes"
wezterm_version = "20230320-124340-559cb7b0"
