[colors]
ansi = [
	"#665c54",
	"#ea6962",
	"#a9b665",
	"#e78a4e",
	"#7daea3",
	"#d3869b",
	"#89b482",
	"#d4be98",
]
background = "#1d2021"
brights = [
	"#928374",
	"#ea6962",
	"#a9b665",
	"#d8a657",
	"#7daea3",
	"#d3869b",
	"#89b482",
	"#d4be98",
]
cursor_bg = "#d4be98"
cursor_border = "#d4be98"
cursor_fg = "#1d2021"
foreground = "#d4be98"
selection_bg = "#d4be98"
selection_fg = "#1d2021"

[colors.indexed]

[metadata]
aliases = []
name = "GruvboxDarkMaterialHard"
origin_url = "https://github.com/mbadolato/iTerm2-Color-Schemes"
wezterm_version = "20230320-124340-559cb7b0"

# # Black
# color0 #665c54
# color8 #928374
#
# # Red
# color1 #ea6962
# color9 #ea6962
#
# # Green
# color2  #a9b665
# color10 #a9b665
#
# # Yellow
# color3  #e78a4e
# color11 #d8a657
#
# # Blue
# color4  #7daea3
# color12 #7daea3
#
# # Magenta
# color5  #d3869b
# color13 #d3869b
#
# # Cyan
# color6  #89b482
# color14 #89b482
#
# # White
# color7  #d4be98
# color15 #d4be98
