name: safetwitch
services:
  safetwitch-frontend:
    container_name: safetwitch-frontend
    hostname: safetwitch-frontend
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    restart: always
    image: codeberg.org/safetwitch/safetwitch:latest
    ports:
      - "127.0.0.1:8280:8280"
    environment:
      - SAFETWITCH_BACKEND_DOMAIN=changethis
      - SAFETWITCH_INSTANCE_DOMAIN=changethis
      - SAFETWITCH_HTTPS=true
      - SAFETWITCH_DEFAULT_LOCALE=en
      - SAFETWITCH_FALLBACK_LOCALE=en

  safetwitch-backend:
    container_name: safetwitch-backend
    hostname: safetwitch-backend
    user: 65534:65534
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: always
    image: codeberg.org/safetwitch/safetwitch-backend:latest
    ports:
      - "127.0.0.1:7100:7000"
    environment:
      - PORT=7000
      - URL=https://changethis
